# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "CallForce" do

pod "MDCSwipeToChoose"
pod "AFNetworking", "~> 2.0"
pod "SWRevealViewController"
pod "IOSLinkedInAPI"

end

target "CallForceTests" do

end

